ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

COPY prom.yml /etc/prometheus/prom.yml
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus"]